### ISSUE TITLE
Repository error during Install

### ISSUE THREAD

**Issue by jimthedj65** [FRINXio/FRINX-machine#145]
Hi All,

I am trying to install FM on a bare minimal ubuntu 18.04 server all up to date and I get an error 
[INFO]: Installing docker-ce
OK
./install.sh: line 76: add-apt-repository: command not found

I think I need to add a repo? any assitance greatly recieved

**Comment by jimthedj65** [comment]
answered: I added the sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
Now I seem to have an error with having too many interfaces and I have to initiate a switch with the docker swarm process.
[INFO]: Initializing docker in swarm mode
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on

making progress. any assistance or guidance on how to specify an interface at install would be great.

**Comment by jimthedj65** [comment]
Ingersting, I ran the install.sh a second time and it completed ok.

**Comment by ChmaraX** [comment]
Hi, 

the bare minimal installation of Ubuntu server probably doesn't include `add-apt-repository`, so we explicitely added installation of package that includes this command and should prevent this issue in the future. 

Regarding the issue with multiple interfaces, please follow instructions in Installation section in recently updated [README](https://github.com/FRINXio/FRINX-machine/blob/master/README.md) 

When starting fm-workflows for the first time, it can take a bit longer to start `sample-topology` - till all devices are mounted, because UniConfig has to load all the models. 

Thanks for feedback, if you have any other issues we are ready to address them.
